IMPORTED_COMPILATION_FLAGS = -O2 -msoft-float -fno-strict-aliasing -fno-common
IMPORTED_TARGET = TARGET_HCF_PCI_LINUX
IMPORTED_ARCH = i386
IMPORTED_FRAMEWORK = FWK_LINUX_HCF
IMPORTED_FRAMEWORK_DEFS = -DFRAME_WORK=FWK_LINUX_HCF -DTARGET_HCF_PCI_LINUX -DNO_V34FAX_SUPPORT -DFRAME_WORK_IMPORTED
IMPORTED_GENERAL_DEFS = 
IMPORTED_DEBUG_DEFS = -DUSE_TRACE
IMPORTED_BLAM_SUPPORT = yes
IMPORTED_SCR_SUPPORT = 
IMPORTED_DMP_SUPPORT = 
IMPORTED_FREE_VERSION = no
IMPORTED_BUILD_TYPE = full
IMPORTED_CNXTLINUXVERSION = 1.21full
